/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

import Backend.Calendarizador;
import Backend.Memoria;
import Backend.Proceso;
import Backend.Tareas; 
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener; 
import java.util.Arrays;
import javax.swing.DefaultRowSorter;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

 
public class Interfaz extends javax.swing.JFrame {  
    Calendarizador calendar = new Calendarizador(); 
    int procesobar=0;
    
    public Interfaz(Calendarizador calendarizador) {
        initComponents(); 
        jTable2.getRowSorter().toggleSortOrder(0);
        jTable4.getRowSorter().toggleSortOrder(3);
        this.calendar = calendarizador;
        Timer timer = new Timer(0, new ActionListener() { 
            @Override
            public void actionPerformed(ActionEvent e) {
                EliminarTablaTareas();
                AgregarTablaTareas();  
                BarraProgreso();
                EliminarTablaMemoria();
                llenarTablaMemoria();
                EliminarTablaMemoriaOrdenados();
                llenarTablaMemoriaOrdenados();
            }
        }); 
        timer.setDelay(100);
        timer.start(); 
    }  
    public void BarraProgreso(){   
        procesobar = calendar.getProcesosTotalesTerminados();
        jProgressBar1.setMinimum(0);
        jProgressBar1.setMaximum(25);
        jProgressBar1.setStringPainted(true);
        jProgressBar1.setBorder(null);
          
        jProgressBar1.setValue(procesobar);
    }  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jl_tareas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jl_memoria = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jl_procesos = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jl_tareas.setText("TABLA DE TAREAS");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num", "Estado", "Tiempo", "Tamaño"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        jl_memoria.setText("TABLA MEMORIA");

        jTable2.setAutoCreateRowSorter(true);
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bloque", "Tamaño ", "Proceso", "Tiempo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(3).setResizable(false);
        }

        jTable4.setAutoCreateRowSorter(true);
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bloque", "Tiempo", "Proceso", "Tiempo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable4);
        if (jTable4.getColumnModel().getColumnCount() > 0) {
            jTable4.getColumnModel().getColumn(0).setResizable(false);
            jTable4.getColumnModel().getColumn(1).setResizable(false);
            jTable4.getColumnModel().getColumn(2).setResizable(false);
            jTable4.getColumnModel().getColumn(3).setResizable(false);
        }

        jl_procesos.setText("TABLA PROCESOS ORDENADOS");

        jProgressBar1.setMaximum(25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_tareas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_memoria))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_procesos)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_tareas)
                    .addComponent(jl_memoria)
                    .addComponent(jl_procesos))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void AgregarTablaTareas() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel(); 
        Object rowData[] = new Object[4];
        Proceso[] procesos = Tareas.getProcesos(); 
        for (Proceso proceso : procesos) {
            Object[] fila = {proceso.getNum(), proceso.getEstado(), proceso.getTiempo(),
                proceso.getTamano()};
            model.addRow(fila); 
        } 
        
    } 
    public void EliminarTablaTareas() {
        DefaultTableModel dm = (DefaultTableModel) jTable1.getModel();
        int rowCount = dm.getRowCount();

        for (int i = rowCount - 1; i >= 0; i--) {
            dm.removeRow(i);
        }
    }
    public void llenarTablaMemoria() {
        Memoria[] bloquesMemoria = calendar.getBloquesMemoria();
        if (bloquesMemoria == null) return;
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel(); 
        for (Memoria bloqueMemoria : bloquesMemoria) {
            if (bloqueMemoria == null || bloqueMemoria.proceso == null) break;
            Object[] fila = {bloqueMemoria.getBloque(), bloqueMemoria.getTamano(), bloqueMemoria.proceso.getNum(),
                bloqueMemoria.proceso.getTiempo()}; 
            model.addRow(fila); 
        }
    } 
    public void EliminarTablaMemoria() {
        DefaultTableModel dm = (DefaultTableModel) jTable2.getModel();
        int rowCount = dm.getRowCount(); 
        for (int i = rowCount - 1; i >= 0; i--) {
            dm.removeRow(i);
        }
    }
    public void llenarTablaMemoriaOrdenados() {
        Memoria[] bloquesMemoriaOrdenados = calendar.getBloquesMemoria();
        if (bloquesMemoriaOrdenados == null) return;
        DefaultTableModel model = (DefaultTableModel) jTable4.getModel(); 
        for (Memoria bloqueMemoriaOrdenados : bloquesMemoriaOrdenados) {
            if (bloqueMemoriaOrdenados == null || bloqueMemoriaOrdenados.proceso == null) break;
            Object[] fila = {bloqueMemoriaOrdenados.getBloque(), 
                bloqueMemoriaOrdenados.getTamano(),
                bloqueMemoriaOrdenados.proceso.getNum(),
                bloqueMemoriaOrdenados.proceso.getTiempo()}; 
            model.addRow(fila); 
        }
    } 
    public void EliminarTablaMemoriaOrdenados() {
        DefaultTableModel dm = (DefaultTableModel) jTable4.getModel();
        int rowCount = dm.getRowCount(); 
        for (int i = rowCount - 1; i >= 0; i--) {
            dm.removeRow(i);
        }
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JLabel jl_memoria;
    private javax.swing.JLabel jl_procesos;
    private javax.swing.JLabel jl_tareas;
    // End of variables declaration//GEN-END:variables

 
}
